export const categoryMap: { [key: number]: string } = {
  11: "Barcelona",
  13: "Baseball",
  25: "Culture",
  5: "Life",
  12: "Movies",
  23: "Music",
  24: "Politics",
  2: "Reviews",
  3: "Sports",
  6: "Stories",
  8: "Study Abroad",
  4: "Tech",
  10: "Television",
  9: "Travel",
};
